### ISSUE TITLE
How to integrate with Flat Weather jQuery Plugin

### ISSUE THREAD

**Issue by online123be** [cartond/flat-weather-darksky-port.js#1]
I am not sure how to integrate this to Flat Weather jQuery Plugin..
Can you please provide me with an example project?

**Comment by cartond** [comment]
Because the plugin is a paid plugin, I can't share any of its code. You will have to add the sections of code in the line numbers denoted.

As for getting data from DarkSky's API, you must implement some sort of backend to get that data.

If you want to post your project, I can look at it for you. I would be careful of posting the plugin because of the above note.

**Comment by online123be** [comment]
Hey, thanks for your reply.
I own the plugin but can't get it to work.. g3x123 on the comments section of the plugin.
Does this give you the 'possibility' to help me out with the implementation?

**Comment by cartond** [comment]
The file has all the information I can give to help you without having your code. Create a private repo and share it with me if you'd like. Again you have to create some back end service to call their API
